{"name": "test_six[30-5-6]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 35 == 6\n +  where 35 = add(30, 5)", "trace": "self = <Work.test_work2.TestB object at 0x10dea3668>, module = None\nclassB_start = None, a = 30, b = 5, expected = 6\n\n    @pytest.mark.parametrize(\"a,b,expected\", json.load(open(\"calc.json\")))\n    def test_six(self, module, classB_start, a, b, expected):\n        # a = json.load(open(\"calc.json\"))\n        # print(a[\"login\"])\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 35 == 6\nE        +  where 35 = add(30, 5)\n\ntest_work2.py:45: AssertionError"}, "attachments": [{"name": "log", "source": "d978c1ec-1e66-4198-9a6a-8dfd3bedf1f9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "38a0320e-731e-430c-a320-def636efb96b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "30"}, {"name": "b", "value": "5"}, {"name": "expected", "value": "6"}], "start": 1573546636395, "stop": 1573546636395, "uuid": "c53a3db1-44f9-4837-8187-bf3553720f6d", "historyId": "f705f0da69ea3fd522db0cdf7598df1d", "testCaseId": "4f6de44d5dec1d8b69075d2b48ad4434", "fullName": "test_work2.TestB#test_six", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}