{"name": "test_add[5-7-9]", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed!!!\nassert 9 == 12", "trace": "self = <Work.test_params.TestParams object at 0x10df4e128>, a = 5, b = 7\nexpected = 9\n\n    @allure.description(\"加法计算\")\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9),\n                                              (4, 4, 8),\n                                              (9, 9, 18),\n                                              (40, 40, 1),\n                                              (6, 5, 30)])\n    def test_add(self, a, b, expected):\n        sum = add(a, b)\n>       assert expected == sum, \"Test Failed!!!\"\nE       AssertionError: Test Failed!!!\nE       assert 9 == 12\n\ntest_params.py:51: AssertionError"}, "description": "加法计算", "attachments": [{"name": "log", "source": "c9e1c78d-56c5-41bc-bc39-bfc91f2a7ecc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c821deee-4733-4e31-8e82-9196f391e704-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "7"}, {"name": "expected", "value": "9"}], "start": 1573546636504, "stop": 1573546636504, "uuid": "038e659d-6470-46a2-a146-1123906bd586", "historyId": "0eb9a4f5e5f04a49166bf97c3c0694f2", "testCaseId": "5e9e0a754422f4a1cda34a85c2742411", "fullName": "test_params.TestParams#test_add", "labels": [{"name": "suite", "value": "test_params"}, {"name": "subSuite", "value": "TestParams"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_params"}]}