{"name": "test_six[6-9-13]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 15 == 13\n +  where 15 = add(6, 9)", "trace": "self = <Work.test_work.TestB object at 0x10df21198>, a = 6, b = 9, expected = 13\n\n    @pytest.mark.parametrize(\"a,b,expected\", json.load(open(\"calc.json\")))\n    def test_six(self, a, b, expected):\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 15 == 13\nE        +  where 15 = add(6, 9)\n\ntest_work.py:58: AssertionError"}, "attachments": [{"name": "log", "source": "6a48cb7d-5f20-48d9-bb8a-c67aebbb0b7c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "28f207d0-0fce-45d1-9d09-89d66a4fe53b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "6"}, {"name": "b", "value": "9"}, {"name": "expected", "value": "13"}], "start": 1573546636460, "stop": 1573546636460, "uuid": "baa44e40-a3e8-48f7-aca2-c1fcfedd0951", "historyId": "fe82b554876d75cd5a307d34c53dd79f", "testCaseId": "33cda52eda96a5e8528fcc03f1cd347a", "fullName": "test_work.TestB#test_six", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}