{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work.TestB object at 0x1020de6d8>\n\n    def test_five(self):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work.py:53: AssertionError"}, "attachments": [{"name": "log", "source": "fc864414-762e-48ab-84e4-e1e972d03bd1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "968e578b-1b5d-4b2a-865c-4e388b6e2ba6-attachment.txt", "type": "text/plain"}], "start": 1572057907168, "stop": 1572057907168, "uuid": "21c9ae99-d7cb-44c2-8958-0efedeb4cb87", "historyId": "29300f720fe0109f83442a8fb4bb3911", "testCaseId": "f779b13c2b9c2dc87d78ea24bb4c7d7a", "fullName": "test_work.TestB#test_five", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6382-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}