{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work2.TestB object at 0x100fca588>, module = None\nclassB_start = None\n\n    def test_five(self, module, classB_start):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "a39c1fde-b470-4d57-9309-820f10d444f0-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8bb30adb-6e93-49fd-85fc-f91e9f9908dd-attachment.txt", "type": "text/plain"}], "start": 1572057907080, "stop": 1572057907081, "uuid": "36dba706-e26a-458e-b252-e8508595dd61", "historyId": "f404a0e497806cca9f97bd6ab5a0dc79", "testCaseId": "1c304be36e911a2dc5dc41fae2b8e66a", "fullName": "test_work2.TestB#test_five", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6382-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}