{"name": "test_nine[3-3-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = add(3, 3)", "trace": "self = <Work.test_work.TestC object at 0x100fbd7f0>, a = 3, b = 3, expected = 9\n\n    @pytest.mark.run(order=2)\n    # @pytest.mark.run('second')\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 6 == 9\nE        +  where 6 = add(3, 3)\n\ntest_work.py:81: AssertionError"}, "attachments": [{"name": "log", "source": "cd48ea94-4032-4563-b39b-03877500b784-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "3e44c076-f441-41ec-b588-a93d26366776-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "3"}, {"name": "expected", "value": "9"}], "start": 1572057907018, "stop": 1572057907018, "uuid": "13d70f5e-6775-40e7-8f95-91053107a681", "historyId": "1e47cfe1eb37baeaa0c789e5434618f6", "testCaseId": "94eee2a481c08a178297ee94c3c1d95a", "fullName": "test_work.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6382-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}