{"name": "test_nine[8-6-2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 2\n +  where 14 = add(8, 6)", "trace": "self = <Work.test_work.TestC object at 0x10d8eb2e8>, a = 8, b = 6, expected = 2\n\n    @pytest.mark.run(order=2)\n    # @pytest.mark.run('second')\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 14 == 2\nE        +  where 14 = add(8, 6)\n\ntest_work.py:81: AssertionError"}, "attachments": [{"name": "log", "source": "dc4f56cf-dbcd-43f4-b865-0cb6c56002e7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9e556c55-6cce-4ad5-9f95-092a61e85f18-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "8"}, {"name": "b", "value": "6"}, {"name": "expected", "value": "2"}], "start": 1571556242373, "stop": 1571556242373, "uuid": "7bab80b8-8e1b-4afb-a22a-d5ffa2acc4e4", "historyId": "1421ced879ca407d6d0fe92ae584a01a", "testCaseId": "94eee2a481c08a178297ee94c3c1d95a", "fullName": "test_work.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "9724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}