{"name": "test_nine[3-3-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = add(3, 3)", "trace": "self = <Work.test_work2.TestC object at 0x10ec03f98>, module = None, a = 3\nb = 3, expected = 9\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, module, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 6 == 9\nE        +  where 6 = add(3, 3)\n\ntest_work2.py:63: AssertionError"}, "attachments": [{"name": "log", "source": "ca993457-7a09-4f5a-ade3-5b5d0b651df2-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f46b0066-fc67-424e-bdce-9d377725c2a0-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "3"}, {"name": "expected", "value": "9"}], "start": 1571556242252, "stop": 1571556242253, "uuid": "be80395b-06c9-4540-b471-e4e14339300c", "historyId": "a9f61db0126d0ac07307c6847cb6dfbf", "testCaseId": "34948f2ea323885fecbb4c0c730ce3c1", "fullName": "test_work2.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "9724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}