{"name": "test_three[5-7-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 9\n +  where 12 = add(5, 7)", "trace": "self = <Work.test_work.TestA object at 0x1111554e0>, a = 5, b = 7, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9)])\n    def test_three(self, a, b, expected):\n        logging.info(\"This is test_three!!!\")\n>       assert add(a, b) == expected\nE       assert 12 == 9\nE        +  where 12 = add(5, 7)\n\ntest_work.py:40: AssertionError"}, "attachments": [{"name": "log", "source": "fdf85666-a077-4100-8b9d-8215cef095ae-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "bf88074e-f64d-4601-bc48-7ff45ebdb715-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "7"}, {"name": "expected", "value": "9"}], "start": 1570675352116, "stop": 1570675352116, "uuid": "ea0f0382-44d7-483c-b087-41bf8f4372a2", "historyId": "a6b207f2237805b0c194c46fc5dca99c", "testCaseId": "b4ca08758d21ef2bc07ba7322d4fdacc", "fullName": "test_work.TestA#test_three", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestA"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "28698-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}