{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work2.TestB object at 0x104e6c208>, module = None\nclassB_start = None\n\n    def test_five(self, module, classB_start):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "26900fec-4366-4481-b6bd-db69c301392a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6b24dcd1-d975-4de1-a361-9d404736c686-attachment.txt", "type": "text/plain"}], "start": 1572059932526, "stop": 1572059932526, "uuid": "2917288d-619f-48ef-bc8d-7f77bdd20819", "historyId": "f404a0e497806cca9f97bd6ab5a0dc79", "testCaseId": "1c304be36e911a2dc5dc41fae2b8e66a", "fullName": "test_work2.TestB#test_five", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "7295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}