{"name": "test_three[5-7-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 9\n +  where 12 = add(5, 7)", "trace": "self = <Work.test_work2.TestA object at 0x104e4d6d8>, module = None\nclassA_end = None, a = 5, b = 7, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9)])\n    def test_three(self, module, classA_end, a, b, expected):\n        logging.info(\"This is test_three!!!\")\n>       assert add(a, b) == expected\nE       assert 12 == 9\nE        +  where 12 = add(5, 7)\n\ntest_work2.py:28: AssertionError"}, "attachments": [{"name": "log", "source": "7c36461d-c401-4be9-bda2-a03195982d5f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "77663343-ad68-463f-92dd-9ff4f4c9f798-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "7"}, {"name": "expected", "value": "9"}], "start": 1572059932507, "stop": 1572059932508, "uuid": "74e2fe68-6514-4413-8edd-bc3a2dcbb97f", "historyId": "67788ebee6ba081243870e930b32a23f", "testCaseId": "654440bd0d0559254558d9c8c3f84b7b", "fullName": "test_work2.TestA#test_three", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestA"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "7295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}