{"name": "test_nine[8-6-2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 2\n +  where 14 = add(8, 6)", "trace": "self = <Work.test_work2.TestC object at 0x10b3293c8>, module = None, a = 8\nb = 6, expected = 2\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, module, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 14 == 2\nE        +  where 14 = add(8, 6)\n\ntest_work2.py:63: AssertionError"}, "attachments": [{"name": "log", "source": "3cf6edc6-0730-4475-a4bc-015d9d9766d6-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1ec17b99-dee9-4ec3-b56c-773b6d603079-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "8"}, {"name": "b", "value": "6"}, {"name": "expected", "value": "2"}], "start": 1572058204648, "stop": 1572058204650, "uuid": "82e99293-5d9b-42cb-8655-dc8603544fd7", "historyId": "904f4ded503097a82b391ed078273134", "testCaseId": "34948f2ea323885fecbb4c0c730ce3c1", "fullName": "test_work2.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}