{"name": "test_nine[3-3-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = add(3, 3)", "trace": "self = <Work.test_work2.TestC object at 0x10b3292b0>, module = None, a = 3\nb = 3, expected = 9\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, module, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 6 == 9\nE        +  where 6 = add(3, 3)\n\ntest_work2.py:63: AssertionError"}, "attachments": [{"name": "log", "source": "8348eb27-15a2-413e-a8c7-118281c590ff-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a808ee4a-fab3-4c54-8801-a83ca04b56d1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "3"}, {"name": "expected", "value": "9"}], "start": 1572058204575, "stop": 1572058204575, "uuid": "b8d851d2-62a4-40d2-a4f4-5746143fa485", "historyId": "a9f61db0126d0ac07307c6847cb6dfbf", "testCaseId": "34948f2ea323885fecbb4c0c730ce3c1", "fullName": "test_work2.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}