{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work.TestB object at 0x10b51c6a0>\n\n    def test_five(self):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work.py:53: AssertionError"}, "attachments": [{"name": "log", "source": "99bd8861-3b9e-4994-b93a-6d2bb1b32109-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "701d8c30-094d-41c7-b694-d6fb87dd57c3-attachment.txt", "type": "text/plain"}], "start": 1572058204794, "stop": 1572058204795, "uuid": "dfe69310-93cd-4525-95f7-99718e4830be", "historyId": "29300f720fe0109f83442a8fb4bb3911", "testCaseId": "f779b13c2b9c2dc87d78ea24bb4c7d7a", "fullName": "test_work.TestB#test_five", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}