{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work2.TestB object at 0x10b51c2b0>, module = None\nclassB_start = None\n\n    def test_five(self, module, classB_start):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "bc15a904-c96b-4f9b-a03c-9e7577b0e46d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8754e6fb-988e-4fd9-8c0e-46160facc11a-attachment.txt", "type": "text/plain"}], "start": 1572058204723, "stop": 1572058204723, "uuid": "57ab36bb-eca8-4f7c-89f9-0e3fed0bc62b", "historyId": "f404a0e497806cca9f97bd6ab5a0dc79", "testCaseId": "1c304be36e911a2dc5dc41fae2b8e66a", "fullName": "test_work2.TestB#test_five", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "6564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}