{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work2.TestB object at 0x10b28b978>, module = None, classB_start = None\n\n    def test_five(self, module, classB_start):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "56d3ce5b-5b4c-45ce-9ebd-9899566eab0f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e530cbdc-7aa2-4f51-a35c-802403f3021c-attachment.txt", "type": "text/plain"}], "start": 1571538979023, "stop": 1571538979024, "uuid": "abc189e3-1a6b-43ff-b50a-a28db7579e06", "historyId": "f404a0e497806cca9f97bd6ab5a0dc79", "testCaseId": "1c304be36e911a2dc5dc41fae2b8e66a", "fullName": "test_work2.TestB#test_five", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "2205-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}