{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work.TestB object at 0x10b2472e8>\n\n    def test_five(self):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work.py:53: AssertionError"}, "attachments": [{"name": "log", "source": "a526d61d-de5c-4aa5-a602-cb8169947e6f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f85fb6e8-4a00-42bb-8a7f-e456e451d6a1-attachment.txt", "type": "text/plain"}], "start": 1571538978938, "stop": 1571538978938, "uuid": "a6d874ec-85e7-46bb-badb-1de06f00b808", "historyId": "29300f720fe0109f83442a8fb4bb3911", "testCaseId": "f779b13c2b9c2dc87d78ea24bb4c7d7a", "fullName": "test_work.TestB#test_five", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "2205-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}