{"name": "test_nine[3-3-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = add(3, 3)", "trace": "self = <Work.test_work2.TestC object at 0x10b247a20>, module = None, a = 3, b = 3, expected = 9\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, module, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 6 == 9\nE        +  where 6 = add(3, 3)\n\ntest_work2.py:63: AssertionError"}, "attachments": [{"name": "log", "source": "cd3058b2-139c-45fa-936e-8c2a19844111-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "25f208a5-e10a-47b7-996e-d8f816949fcd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "3"}, {"name": "expected", "value": "9"}], "start": 1571538978843, "stop": 1571538978843, "uuid": "1edbd539-b76b-41ed-9778-2d3b962942a9", "historyId": "a9f61db0126d0ac07307c6847cb6dfbf", "testCaseId": "34948f2ea323885fecbb4c0c730ce3c1", "fullName": "test_work2.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ParsondeMacBook-Pro.local"}, {"name": "thread", "value": "2205-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}